name: Deploy Flask + Postgres to EC2 via Docker Compose

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: SSH into EC2 & deploy using Docker Compose
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd /home/ec2-user
          if [ ! -d docker-ecr-auto ]; then
            git clone https://github.com/Uthmanade001/docker-ecr-auto.git
          else
            cd docker-ecr-auto && git pull
          fi

          cd /home/ec2-user/docker-ecr-auto

          docker compose down || true
          docker compose up -d --build

